#coding=utf-8
"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 1.11.16.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import os
import sys 


reload(sys)
sys.setdefaultencoding('utf8')
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0,os.path.join(BASE_DIR,'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@-=qkp1$tuoavhbdnblowi(#jvr&svhy*ymgj1yro&(mb)-5+$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# django认证系统使用的模型类
# 注意： AUTH_USER_MODEL配置参数要在第一次迁移数据库之前配置，否则可能django的认证系统工作不正常
AUTH_USER_MODEL='users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',#副文本编辑器
    'haystack',
    'goods',#商品模块
    'users',#用户模块
    'order',#订单模块
    'cart',#购物车模块
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'NAME':'project',
        'USER':'root',
        'PASSWORD':'as910329',
        'HOST':'localhost',
        'PORT':3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'


#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


#user = authenticate(username=username, password=password)返回结果都是None的解决方法
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
# STATIC_ROOT=os.path.join(BASE_DIR,'/static')
#副文本编辑器配置
TINYMCE_DEFAULT_CONFIG = {
	'theme':'advanced',
	'width':600,
	'height':400,
}

# 发送邮件配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# smpt服务地址
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 25
# 发送邮件的邮箱
EMAIL_HOST_USER = '13046200569@163.com'
# 在邮箱中设置的客户端授权密码as319976,is not login password
EMAIL_HOST_PASSWORD = 'as319976'
# 收件人看到的发件人
EMAIL_FROM = '天天生鲜<13046200569@163.com>'


LOGIN_URL='/users/login' #/accounts/login?next=/user#自动登录的地址

#用redis作为CACHE的缓存，CACHE的配置pip insatll django-redis
CACHES = {
    "default":{
        "BACKEND":"django_redis.cache.RedisCache",
        "LOCATION":"redis://192.168.0.199:6379/9",
        "OPTIONS":{
            "CLIENT_CLASS":"django_redis.client.DefaultClient"   ,
            "PASSWORD":"as910329",    
      }
   },
    "session":{
        "BACKEND":"django_redis.cache.RedisCache",
        "LOCATION":"redis://192.168.0.199:6379/5",
        "OPTIONS":{
            "CLIENT_CLASS":"django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100}, 
            "PASSWORD":"as910329",    
      }
   }
}

#配置session存储，用cache(redis)来保存session
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'   # 引擎（默认）
SESSION_CACHE_ALIAS = "session"
# # Session的cookie保存在浏览器上时的key，即：sessionid＝随机字符串（默认）
# SESSION_COOKIE_NAME="sessionid" 
# # Session的cookie保存的路径（默认）
# SESSION_COOKIE_PATH="/"     
#  # Session的cookie保存的域名（默认）                          
# SESSION_COOKIE_DOMAIN = None                            
#  # 是否Https传输cookie（默认）
# SESSION_COOKIE_SECURE = False                           
#  # 是否Session的cookie只支持http传输（默认）
# SESSION_COOKIE_HTTPONLY = True                          
#  # Session的cookie失效日期（2周）（默认）
# SESSION_COOKIE_AGE = 1209600                            
#  # 是否关闭浏览器使得Session过期（默认）
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False                 
# # 是否每次请求都保存Session，默认修改之后才保存（默认）
# SESSION_SAVE_EVERY_REQUEST = False                       


# #将session的存储位置设为redis数据库
# SESSION_ENGINE='redis_sessions.session'
# #设置服务器ip
# SESSION_REDIS_HOST='192.168.0.199'
# #填写redis端口号
# SESSION_REDIS_PORT=6379
# #选择redis里的1号数据库存储session(redis里有16个数据库，编号从0开始)
# SESSION_REDIS_DB=0
# #填写我的redis密码
# SESSION_REDIS_PASSWORD='as910329'
# #给存入redis里的session加上前缀"session"，便于查找session
# SESSION_REDIS_PREFIX='session'


#django moren zhiding de wenjian xitong设置默认的文件系统为fdfs
DEFAULT_FILE_STORAGE='utils.fdfs.storage.FDFSStorage'
#myself dingyi 
MY_FDFS_CLIENT_CONF='./utils/fdfs/client.conf'#客户端地址
MY_FDFS_URL='http://192.168.0.199:8888/'#fdfs的地址


#全文搜索框架
HAYSTACK_CONNECTIONS = {
    'default':{
        #'ENGINE':'haystack.backends.whoosh_backend.WhooshEngine',
        'ENGINE':'haystack.backends.whoosh_cn_backend.WhooshEngine',#这个是用了jieba分词的
        'PATH':os.path.join(BASE_DIR,'whoosh_index'),
    },
}
#dan tianjia xiugai shanchu shujv zidong shengcheng suoyin当添加修改删除数据的时候，自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'